api/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('products/', views.AllProducts.as_view(), name='api_products'),
    path('products/<int:id>/images/', views.ProductImages.as_view(), name='api_images'),
    path('page/', views.PageImages.as_view(), name='api_page'),
    path('register/', views.RegisterUser, name='api_registration'),
    path('login/', views.LoginUser, name='api_login')
]

ecom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path, include
from store import views

urlpatterns = [
    path('', views.home.as_view(), name='homepage'),
    path('product/<int:pk>', views.product_detail.as_view(), name='product_detail'),
    path('register/', views.signUp, name='register'),
    path('postsignUp/', views.postsignUp),
    path('login/', views.signIn, name='login'),
    path('postsignIn/', views.postsignIn),
    path('fav/<int:id>/', views.favourite_add, name='favourite_add'),
    path('cart/', views.cart_details.as_view(), name='cart_details'),
]

store/models.py
from django.db import models
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver
from django.contrib.auth.models import User


class Product(models.Model):
    title = models.CharField(max_length=50)
    price = models.FloatField(max_length=4)
    description = models.CharField(max_length=250)
    main_image = models.ImageField(upload_to='main_images/', default='default.jpg')




class Image(models.Model):
    #class ImageType(models.TextChoices):
    #    MAIN = ('MN','Main')
    #    SOPHOMORE = ('SC', 'Secondary')

    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    #im_type = models.CharField(max_length=2, choices=ImageType.choices)
    image = models.ImageField(upload_to='product_images/')

class PageImage(models.Model):
    #class ImageType(models.TextChoices):
    #    MAIN_CAROUSEL = ('MC', 'main_carousel')

    image = models.ImageField(upload_to='page_images/')
    #im_type = models.CharField(max_length=40, choices=ImageType.choices)


class FavouriteItems(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)



@receiver(post_delete, sender=Image)
def post_save_image(sender, instance, *args, **kwargs):
    """ Clean Old Image file """
    try:
        instance.image.delete(save=False)
    except:
        pass


@receiver(pre_save, sender=Image)
def pre_save_image(sender, instance, *args, **kwargs):
    """ instance old image file will delete from os """
    try:
        old_img = instance.__class__.objects.get(id=instance.id).image.path
        try:
            new_img = instance.image.path
        except:
            new_img = None
        if new_img != old_img:
            import os
            if os.path.exists(old_img):
                os.remove(old_img)
    except:
        pass


@receiver(post_delete, sender=Product)
def post_save_image(sender, instance, *args, **kwargs):
    """ Clean Old Image file """
    try:
        old_img = str(instance.__class__.objects.get(id=instance.id).main_image.path)
        if not old_img.endswith('default.jpg'):
            instance.main_image.delete(save=False)
    except:
        pass


@receiver(pre_save, sender=Product)
def pre_save_image(sender, instance, *args, **kwargs):
    """ instance old image file will delete from os """
    try:
        old_img = instance.__class__.objects.get(id=instance.id).image.path
        try:
            new_img = instance.image.path
        except:
            new_img = None
        if new_img != old_img and not old_img.endswith('default.jpg'):
            import os
            if os.path.exists(old_img):
                os.remove(old_img)
    except:
        pass


@receiver(post_delete, sender=PageImage)
def post_save_image(sender, instance, *args, **kwargs):
    """ Clean Old Image file """
    try:
        instance.image.delete(save=False)
    except:
        pass


@receiver(pre_save, sender=PageImage)
def pre_save_image(sender, instance, *args, **kwargs):
    """ instance old image file will delete from os """
    try:
        old_img = instance.__class__.objects.get(id=instance.id).image.path
        try:
            new_img = instance.image.path
        except:
            new_img = None
        if new_img != old_img:
            import os
            if os.path.exists(old_img):
                os.remove(old_img)
    except:
        pass

store/views.py
import urllib

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.views.generic import ListView, DetailView
from rest_framework.generics import get_object_or_404

from .models import Product, Image, FavouriteItems
#import pyrebase


# firebaseConfig = {
#   'apiKey': "AIzaSyDBWojLiSvBqKN4pKPl6UPQnVPeTgBkJdc",
#   'authDomain': "ecom-486a3.firebaseapp.com",
#   'projectId': "ecom-486a3",
#   'storageBucket': "ecom-486a3.appspot.com",
#   'messagingSenderId': "294539198516",
#   'appId': "1:294539198516:web:32d9181d298bf097dfca61",
#   'measurementId': "G-QZ0Z8W39P2",
#   'databaseURL': ""
# }
#
# firebase = pyrebase.initialize_app(firebaseConfig)
# authe = firebase.auth()
# database = firebase.database()


class home(ListView):

    model = Product
    context_object_name = 'products'
    template_name = 'store/home.html'

class product_detail(DetailView):

    model = Product
    template_name = 'store/product_info.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        carted = False
        if self.request.user.username != '' and FavouriteItems.objects.all().filter(user=self.request.user,
                                                                               product=Product.objects.get(
                                                                                       id=id)).first():
            carted = True
        context = super().get_context_data(**kwargs)
        context['carted'] = carted
        return context



def signUp(request):
    return render(request,"store/registration.html")


def postsignUp(request):
    email = request.POST.get('email')
    passs = request.POST.get('pass')
    rep_pass = request.POST.get('pass_repeat')
    try:
        if passs != rep_pass:
            raise Exception("Passwords should match")
        if len(passs) < 6:
            raise Exception("Password should be at least 6 characters long")
        # creating a user with the given email and password
        user = User.objects.create_user(email, email, passs)
        user.save()

    except Exception as e:
        print(e)
        msg = str(e)
        content = {
            'message': msg,
        }
        return render(request, "store/registration.html", content)
    return render(request, "store/login.html")




def signIn(request):
    return render(request, "store/login.html")



def postsignIn(request):
    email = request.POST.get('email')
    pasw = request.POST.get('pass')
    try:
        # if there is no error then signin the user with given email and password
        user = authenticate(username=email, password=pasw)
        if user is None:
            raise Exception("")
        request.user = user
    except:
        message = "Invalid Credentials!!"
        return render(request, "store/login.html", {"message": message})
    content = {
        'products': Product.objects.all(),
        'username': request.user.username,
    }
    return render(request, 'store/home.html', content)


@login_required
def favourite_add(request, id):
    product = get_object_or_404(Product, id=id)
    favourite = FavouriteItems.objects.all().filter(user=request.user, product=product).first()
    if favourite:
        favourite.delete()
    else:
        favourite = FavouriteItems.objects.create(user=request.user, product=product)
        favourite.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])



class cart_details(ListView):
    model = Product
    template_name = 'store/cart.html'
    context_object_name = 'products'

    def get_queryset(self):
        products = FavouriteItems.objects.all().filter(user=self.request.user)
        return products

    # content = {}
    # if request.user.username:
    #     products = FavouriteItems.objects.all().filter(user=request.user)
    #     content = {
    #         'products': products,
    #         'username': request.user.username
    #     }
    # return render(request, 'store/cart.html', content)

store/templates/store/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>


    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- FontAwesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet">

     <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'store/styles/styles.css' %}">

</head>
<body style="min-height: 100vh">

    <div class="wrapper">

        <!-- Navigation -->
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light py-3">
                <div class="container-fluid">

                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="fa-solid fa-cart-shopping" href="{% url 'cart_details' %}"
                               style="text-decoration: none; color: black"> Cart</a>
                            {% if request.user.username %}
                                <span class="fa-solid fa-user" href="{% url 'register' %}"> {{ request.user.username }}</span>
                            {% else %}
                                <a class="fa-solid fa-user" style="text-decoration: none; color: black"
                                   href="{% url 'register' %}"> Register</a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </nav>

            <nav class="navbar navbar-expand-lg navbar-light bg-light py-3">
                <div class="container-fluid">
                    <a href="{% url 'homepage' %}"><img src="{% static 'store/images/logo.png' %}" alt="Logo"></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'homepage' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Hot</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Shop</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Contacts</a>
                            </li>
                        </ul>
                        <form class="d-flex">
                            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                    </div>
                </div>
            </nav>
        </header>

        <main class="main mt-5">
            {% block content %}{% endblock %}
        </main>

        <!-- Footer -->
        <footer class="bg-dark text-center text-white">
            <div class="container p-4">
                <section class="ms-4">
                    <span class="fab fa-facebook-f"></span>
                    <span class="fab fa-twitter"></span>
                </section>
            </div>
            <div class="text-center p-3">
                © 2022 Copyright: Company
            </div>
        </footer>

    </div>

<!-- Bootstrap -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

store/templates/store/cart.html
{% extends 'store/base.html' %}
{% block content %}

    {% if products %}
        <section class="p-5 container">
            <div class="container py-5">
                <h1>Cart<span class="fa-solid fa-cart-shopping p-2"></span></h1>
            </div>
            <div class="row">
                {% for prod in products %}
                    <div class="mx-auto card col-lg-2 col-md-4 col-7 p-1 mb-4 py-3">
                        <a href="/product/{{ prod.product.id }}" style="text-decoration: none; color: grey">
                            <img src="{{ prod.product.main_image.url }}" class="card-img-top im1" alt="...">

                            <div class="card-body">
                                <h5 class="card-title">{{ prod.product.title }}</h5>
                                <p class="card-text" style="text-align: center">{{ prod.product.price }} $</p>
                                <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </section>
    {% elif request.user.username %}
         <div class="container">
            <h3 style="text-align: center" class="py-5">There are no items yet</h3>
        </div>
    {% else %}
        <div class="container">
            <h3 style="text-align: center" class="py-5">You have to <a href="{% url 'register' %}">login</a> first</h3>
        </div>
    {% endif %}
{% endblock %}

store/templates/store/home.html
{% extends "store/base.html" %}
{% load static %}
{% block content %}


    <!-- Carousel -->
    <div id="carouselBanner" class="carousel slide py-7" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'store/images/4.jpg' %}" class="d-block w-100 carousel-image" alt="Hello">
            </div>
            <div class="carousel-item">
                <img src="{% static 'store/images/2.png' %}" class="d-block w-100 carousel-image" alt="Welcome">
            </div>
            <div class="carousel-item">
                <img src="{% static 'store/images/3.jpg' %}" class="d-block w-100 carousel-image" alt="Bonjourne">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselBanner" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true" style="background-color: gray"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselBanner" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true" style="background-color: gray"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>



    <!-- Hot -->
    <section class="p-5 container">
        <div class="container py-5">
            <h1>Hot<span class="fa-solid fa-fire p-2" style="color: red"></span></h1>
        </div>
        <div class="row">
            {% for p in products %}
                <div class="mx-auto card col-lg-2 col-md-4 col-7 p-1 mb-4 py-3">
                    <a href="/product/{{p.id}}" style="text-decoration: none; color: grey">
                        <img src="{{ p.main_image.url }}" class="card-img-top im1" alt="...">

                        <div class="card-body">
                            <h5 class="card-title">{{ p.title }}</h5>
                            <p class="card-text" style="text-align: center">{{ p.price }} $</p>
                            <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
                        </div>
                    </a>
                </div>
            {%  endfor %}

        </div>
    </section>

{% endblock %}

store/templates/store/login.html
{% extends 'store/base.html' %}
{% block content %}

    {% if message %}
        <div class="container mx-auto text-center">
            <p style="color: red">{{ message }}</p>
        </div>
    {% endif %}

    <div class="container mx-auto p-5">
        <form action="/postsignIn/" method="post">
            {% csrf_token %}
            <h1>Sign In</h1>
            <p class="py-3">Please fill in this form</p>


            <!-- Email: -->
            <div class="form-group row">
                <label for="Email" class="col-sm-4 col-form-label">Email</label>
                <div class="col-sm-8">
                    <input type="email" id="Email" name="email" placeholder="Your Email Id"><br><br>
                </div>
            </div>
            <!-- Password: -->
            <div class="form-group row">
                <label for="Password" class="col-sm-4 col-form-label">Password</label>
                <div class="col-sm-8">
                    <input type="password" id="Password" name="pass" placeholder="Password"><br><br>
                </div>
            </div>
            <br>
            <br>
            <input type="submit" class="btn btn-primary mb-2" value="Sign In"><br><br>

        </form>
    </div>

{% endblock %}

store/templates/store/product_info.html
{% extends "store/base.html" %}
{% load static %}
{% block content %}

    <div class="container">
        <div class="row">
           <div id="productCarousel" class="carousel slide col-12 col-sm-9 col-md-7 col-lg-5" data-ride="carousel">
               <div class="carousel-inner" role="listbox">
                   <div class="carousel-item active">
                       <img src="{{ product.main_image.url }}" class="d-block img-fluid im2" alt="First slide">
                   </div>
                   {% for im in product.image_set.all %}
                       <div class="carousel-item">
                           <img src="{{ im.image.url }}" class="d-block img-fluid im2" alt="Second slide">
                       </div>
                   {% endfor %}
               </div>
               <a class="carousel-control-prev" href="#productCarousel" role="button" data-bs-slide="prev">
                   <span><i class="fa fa-angle-left fa-3x" style="color: burlywood;" aria-hidden="true"></i></span>
                   <span class="sr-only">Previous</span>
               </a>
               <a class="carousel-control-next" href="#productCarousel" role="button" data-bs-slide="next">
                   <span><i class="fa fa-angle-right fa-3x" style="color: burlywood;" aria-hidden="true"></i></span>
                   <span class="sr-only">Next</span>
               </a>
           </div>

            <div class="col-12 col-sm-3 col-md-5 col-lg-7 py-5 px-4">
                <!-- % url 'favourite_add' product.id %} -->
                <h2 style="text-align: center; display: inline">{{ product.title }}</h2>
                <p style="text-align: center; padding-top: 2vh">{{ product.description }}</p>
                <p style="color: darkgrey; text-align: center" class="px-2">{{ product.price }} $</p>
                <p style="text-align: center" class="py-3">
                    {% if user.username %}
                        {% if not carted %}
                            <a class="btn btn-primary" href="{% url 'favourite_add' product.id %}">Add to cart</a>
                        {% else %}
                            <a class="btn btn-primary" href="{% url 'favourite_add' product.id %}">Remove from cart</a>
                        {% endif %}
                    {% else %}
                        <a class="btn btn-primary" onclick="showAlert()">Add to cart</a>
                    {% endif %}
                </p>
            </div>
        </div>
    </div>

    <script>
        function showAlert() {
            alert ("You have to log in first");
        }
   </script>

{% endblock %}

store/templates/store/registration.html
{% extends 'store/base.html' %}
{% block content %}

    {% if message %}
        <div class="container mx-auto text-center">
            <p style="color: red">{{ message }}</p>
        </div>
    {% endif %}

    <div class="container mx-auto p-5">
        <form action="/postsignUp/" method="post">
            {% csrf_token %}
            <h1>Sign Up</h1>
            <p class="py-3">Please fill in this form</p>


            <!-- Email: -->
            <div class="form-group row">
                <label for="Email" class="col-sm-4 col-form-label">Email</label>
                <div class="col-sm-8">
                    <input type="email" id="Email" name="email" placeholder="Your Email Id"><br><br>
                </div>
            </div>
            <!-- Password: -->
            <div class="form-group row">
                <label for="Password" class="col-sm-4 col-form-label">Password</label>
                <div class="col-sm-8">
                    <input type="password" id="Password" name="pass" placeholder="Password"><br><br>
                </div>
            </div>
            <!-- RepeatPassword: -->
            <div class="form-group row">
                <label for="confirm_password" class="col-sm-4 col-form-label">Confirm Password</label>
                <div class="col-sm-8">
                    <input type="password" id="pass_repeat" name="pass_repeat"
                           placeholder=" Repeat Password"><br><br>
                </div>
            </div>
            <br>
            <br>
            <input type="submit" class="btn btn-primary mb-2" value="SignUp"><br><br>
            <br>
            <p style="text-align: center">Already have account? <a href="{% url 'login' %}">Login</a></p>
        </form>
    </div>



{% endblock %}